name: C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up CMake
      run: sudo apt-get install cmake
    - name: Install Google Test
      run: |
        sudo apt-get install -y libgtest-dev
        cd /usr/src/gtest
        sudo cmake .
        sudo make
        sudo cp *.a /usr/lib
    - name: Build and Test
      run: |
        mkdir build
        cd build
        cmake ..
        cmake --build .
        ctest
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: PaymentStrategyApp
        path: build/PaymentStrategyApp
